### ISSUE TITLE
verify_otp returns otp_counter or nil

### ISSUE THREAD

**Issue by andrezimpel** [stas/otp-jwt#16]
First of all, awesome gem! :-)

In the docs is stated that verify_otp will return true on success and false on failure. In my case if it's true it returns the otp_counter and if its false nil. I made a local patch that return `!otp_status.nil?` instead of `otp_status`.

Is retuning the counter or nil intended?

**Comment by stas** [comment]
@andrezimpel thank you!

Yeah, I think you're right, the docs are off. Feel free to send a PR and I'll happily merge it :heart:

**Comment by ayerdines** [comment]
Hey guys!! I want to work on this issue, can I issue a PR to make `OTP::ActiveRecord#verify_otp` return `true` on success and `false` on failure?

**Comment by ayerdines** [comment]
@stas could you please accommodate some time to review my PR? Thank you!! 🙏
