### ISSUE TITLE
Is there any example app available?

### ISSUE THREAD

**Issue by flyingboy007** [stas/otp-jwt#6]

**Comment by stas** [comment]
Hey @flyingboy007 
would you consider this an example?
https://github.com/stas/otp-jwt/blob/master/spec/dummy.rb

This is a dummy app we're using to run the tests...

**Comment by flyingboy007** [comment]
Hi, Thank you for that. But Still, I couldn't figure out how OTP can be generated for this. 
For ` jwt_from_otp(user, params[:otp]) ` we need to pass an OTP right? But for that first, we need to send that to the client. So how to generate the otp token?

**Comment by stas** [comment]
@flyingboy007 this is covered in the docs, there's `YourModel#otp` method:
https://github.com/stas/otp-jwt#otp-for-active-record-models

In the example above, `params[:otp]` reflects the request parameters, which are sent **by the user**.

**Comment by flyingboy007** [comment]
Yes just figured that out. Sorry for missing that part and thank you for your support.
